from typing import List
from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session
from app.core.database import get_db
from app.core.auth import get_current_user
from app.models.user import User
from app.models.product import ProductDescription
from app.schemas.product_log import ProductLog

router = APIRouter()

@router.get("/logs", response_model=List[ProductLog])
def get_user_logs(db: Session = Depends(get_db), current_user: User = Depends(get_current_user)):
    """Retrieve all product descriptions generated by the current user."""
    return db.query(ProductDescription).filter(ProductDescription.user_id == current_user.id).all()